package com.msoula.catlife.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF77574e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_secondary = Color( 0xFFb02e07)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_background = Color(0xFFfffbff)
val md_theme_light_onBackground = Color(0xFF201a19)
val md_theme_light_surface = Color(0xFFfffbff)
val md_theme_light_onSurface = Color(0xFF201a19)
val md_theme_light_backgroundSwitch = Color(0xFFDAE2E4)

val md_theme_dark_primary = Color(0xFFffb4a1)
val md_theme_dark_onPrimary = Color(0xFF611300)
val md_theme_dark_secondary = Color(0xFFe7bdb3)
val md_theme_dark_onSecondary = Color(0xFF442a23)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF201a19)
val md_theme_dark_onBackground = Color(0xFFede0dd)
val md_theme_dark_surface = Color(0xFF201a19)
val md_theme_dark_onSurface = Color(0xFFede0dd)
val md_theme_dark_backgroundSwitch = Color(0xFF3a313a)